set tabstop=2
set shiftwidth=2
set expandtab
set hlsearch
set fileformat=unix
set fileformats=unix,dos
set ignorecase
set smartcase
au FileType gitcommit set tw=72
"Remove all trailing whitespace by pressing F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
