set tabstop=2
set shiftwidth=2
set expandtab
set hlsearch
set fileformat=unix
set fileformats=unix,dos
set ignorecase
set smartcase
au FileType gitcommit set tw=72
au FileType make setlocal noexpandtab
"Remove all trailing whitespace by pressing F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

if &term =~ '^screen'
    " tmux will send xterm-style keys when its xterm-keys option is on
    execute "set <xUp>=\e[1;*A"
    execute "set <xDown>=\e[1;*B"
    execute "set <xRight>=\e[1;*C"
    execute "set <xLeft>=\e[1;*D"
endif
