#  X Windows startup file

# start in home
if [ "$PWD" != "$HOME" ]; then
  cd "${HOME}" || exit 1
fi

# settings
bell=0
dmps=0
xrdb=1
xmodmap=0
wmname=1
pulseaudio=1
xautolock=1
autocutsel=0

wm=dwm

# bell
if [ $bell -eq 1 ]; then
  xset b on &
else
  xset b off &
fi

# dmps
if [ $dmps -eq 1 ]; then
  xset +dpms &
  xset s on &
else
  xset -dpms &
  xset s off &
fi

# xrdb
if [ $xrdb -eq 1 ]; then
  if [ -f "${HOME}/.Xresources" ]; then
    xrdb -merge "${HOME}/.Xresources" &
  fi
fi

# xmodmap
if [ "$xmodmap" -eq 1 ]; then
  if [ -f "${HOME}/.Xmodmap" ]; then
    xmodmap "${HOME}/.Xmodmap" &
  fi
fi

# wmname fixes some java bugs on (dwm, wmii)
if [ $wmname -eq 1 ]; then
  wmname LG3D &
fi

# pulseaudio
if [ "$pulseaudio" -eq 1 ]; then
  if ! pulseaudio --check >/dev/null 2>&1; then
    start-pulseaudio-x11 2>&1 &
  fi
fi

# xautolock
if [ "$xautolock" -eq 1 ]; then
  if command -v slock >/dev/null 2>&1; then
    xautolock -detectsleep -time 5 -locker slock -000 &
    xss-lock slock &
  fi
fi

# autocutsel
if [ $autocutsel -eq 1 ]; then
  autocutsel -selection PRIMARY -fork &
  autocutsel -selection CLIPBOARD -fork &
fi

# make touchpad tapping work
xinput set-prop "$(xinput --list | grep -i touchpad | head -n 1 | awk '{print $6}' | cut -d'=' -f2)" "libinput Tapping Enabled" 1 &

# to work around Java applications not working properly
export _JAVA_AWT_WM_NONREPARENTING=1

# local xft to avoid issue with icons in the menu in old verions
LD_LIBRARY_PATH=${HOME}/opt/libxft-libXft-2.3.6/lib
if [ -d "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH
fi

# required for dbus to know the graphical environment
# shellcheck disable=SC2046
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

systemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
  dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# work around slowness opening applications, kudos to @gonzaru
export XDG_CURRENT_DESKTOP=dwm
export XDG_SESSION_DESKTOP=dwm
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export DBUS_SESSION_BUS_ADDRESS=unix:path=${XDG_RUNTIME_DIR}/bus

# to properly scale alacritty in secondary screen
export WINIT_X11_SCALE_FACTOR=1.5

# dwm
if [ "$wm" = "dwm" ]; then
  # background color
  xsetroot -solid '#333333' &

  while :; do
    if command -v wmbarupdate >/dev/null 2>&1; then
      wmbarupdate &
    else
      xsetroot -name "$(date +"%a %b %e %H:%M")" &
    fi
    if command -v wmclocksleep >/dev/null 2>&1; then
      sleep "$(wmclocksleep)"
    else
      sleep $((60 - $(/bin/date +%S | sed 's/^0\([0-9]\)/\1/')))
    fi
    # make sure that loop does not exist when X is killed
    if ! ps uxw | grep -qE ' /?[x]init '; then
      break
    fi
  done &
  # $! pid of last bg process
  pidbarloop=$!

  while :; do
    if [ $wm = "dwm" ]; then
      dwm > "$HOME"/.local/share/dwm/dwm.log 2>&1
    fi
    if [ "$(printf 'no\nyes' | dmenu -p "Do you want to quit ${wm}?")" = "yes" ]; then
      # double check
      if [ "$(printf 'no\nyes' | dmenu -p "Again, Do you want to quit ${wm}?")" = "yes" ]; then
        break
      fi
    fi
  done

  # kill previous loop if exists (no zombie)
  if [ -n "$pidbarloop" ]; then
    kill $pidbarloop
    if ps -p "$pidbarloop" >/dev/null 2>&1; then
        kill -KILL "$pidbarloop"
    fi
  fi
fi
